version: '3.4'

services:
  microservicea:
    image: nikheelcapita/repo1:v3
    ports:
      - "8017:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - micro-a-db
    environment:
      - ConnectionStrings__DefaultConnection=Server=micro-a-db;Database=School;uid=sa;pwd=P@ssw0rd;MultipleActiveResultSets=true

  micro-a-db:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd