apiVersion: v1
kind: Pod
metadata:
  name: microservice-a
spec:
  containers:
  - name: microservice-a
    image: nikheelcapita/repo1:v3
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
